# Generated by Django 4.0.3 on 2022-04-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='kids_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
